# Generated by Django 4.1.7 on 2023-04-26 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=25)),
                ('password', models.CharField(max_length=8)),
                ('massages', models.CharField(max_length=500)),
            ],
        ),
    ]
